import type { GeneratedFile } from "../templates/types.ts";
import type { DeliveryReceipt, DeliveryRequest, DeliveryTarget } from "./delivery.ts";

/**
 * `DeliveryTarget` that opens a draft pull request in a repository the
 * customer owns, via the GitHub Git Data API — spoken to directly over
 * `fetch`, for the same reason `SupabaseStore` skips supabase-js: the
 * project's only dependency exception is the Anthropic SDK, and five REST
 * calls do not earn a second one.
 *
 * The sequence is create-only and fails loudly rather than converging: a
 * tree and commit are built on top of the base branch, a new ref is created
 * (never updated, never force-pushed), and a draft PR is opened from it. If
 * the branch already exists — a previous delivery of the same project, or a
 * crash after the ref was created — the delivery fails with GitHub's 422
 * rather than overwriting history, and the operator decides what the second
 * delivery should be called. Like every target, this runs only after
 * `ApprovalGate` has recorded a named human's decision.
 */
export interface GitHubDeliveryOptions {
  /** Repository owner (user or organization). */
  owner: string;
  /** Repository name, without the owner prefix. */
  repo: string;
  /** Token with `contents: write` and `pull-requests: write` on the repo. */
  token: string;
  /** Branch the PR targets. Defaults to the repository's default branch. */
  baseBranch?: string;
  /** Prepended to the project name to form the head branch. */
  branchPrefix?: string;
  /** Directory inside the repo to deliver into. Defaults to the repo root. */
  pathPrefix?: string;
  /** Defaults to `https://api.github.com`. */
  apiUrl?: string;
  /** Injectable for tests; defaults to the global `fetch`. */
  fetchImpl?: typeof fetch;
}

export class GitHubPullRequestDelivery implements DeliveryTarget {
  readonly name = "github-pull-request";
  readonly #options: Required<Pick<GitHubDeliveryOptions, "owner" | "repo" | "token">> &
    GitHubDeliveryOptions;
  readonly #fetch: typeof fetch;
  readonly #apiUrl: string;
  readonly #prefix: string;

  constructor(options: GitHubDeliveryOptions) {
    if (!options.owner || !options.repo || !options.token) {
      throw new Error("GitHubPullRequestDelivery requires owner, repo and token");
    }
    this.#options = options;
    this.#fetch = options.fetchImpl ?? fetch;
    this.#apiUrl = (options.apiUrl ?? "https://api.github.com").replace(/\/+$/, "");
    this.#prefix = normalizePrefix(options.pathPrefix);
  }

  async deliver(request: DeliveryRequest): Promise<DeliveryReceipt> {
    if (request.files.length === 0) {
      throw new Error("refusing to open a pull request with no files");
    }
    const tree = request.files.map((file) => ({
      path: this.#prefix + safeRepoPath(file),
      mode: "100644" as const,
      type: "blob" as const,
      content: file.contents,
    }));

    const base = this.#options.baseBranch ?? (await this.#defaultBranch());
    const baseSha = await this.#baseCommitSha(base);
    const branch = `${this.#options.branchPrefix ?? "andromeda/"}${request.projectName}`;

    const treeSha = (
      await this.#call<{ sha: string }>("POST", "/git/trees", { base_tree: baseSha, tree })
    ).sha;
    const commitSha = (
      await this.#call<{ sha: string }>("POST", "/git/commits", {
        message: `Add ${request.projectName} (approved by ${request.approvedBy})`,
        tree: treeSha,
        parents: [baseSha],
      })
    ).sha;
    await this.#call("POST", "/git/refs", { ref: `refs/heads/${branch}`, sha: commitSha });

    const pr = await this.#call<{ html_url: string }>("POST", "/pulls", {
      title: `Add ${request.projectName}`,
      head: branch,
      base,
      draft: true,
      body:
        `Generated by the Andromeda auto-builder and approved for delivery by ` +
        `${request.approvedBy}. ${request.files.length} file(s); every generated ` +
        `feature passed its frozen tests before this was offered for approval.`,
    });

    return { target: this.name, location: pr.html_url, fileCount: request.files.length };
  }

  async #defaultBranch(): Promise<string> {
    return (await this.#call<{ default_branch: string }>("GET", "")).default_branch;
  }

  async #baseCommitSha(base: string): Promise<string> {
    const ref = await this.#call<{ object: { sha: string } }>(
      "GET",
      `/git/ref/${encodeURIComponent(`heads/${base}`)}`,
    );
    return ref.object.sha;
  }

  async #call<T>(method: "GET" | "POST", path: string, body?: unknown): Promise<T> {
    const url = `${this.#apiUrl}/repos/${this.#options.owner}/${this.#options.repo}${path}`;
    const res = await this.#fetch(url, {
      method,
      headers: {
        authorization: `Bearer ${this.#options.token}`,
        accept: "application/vnd.github+json",
        "x-github-api-version": "2022-11-28",
        "user-agent": "andromeda-autobuilder",
        ...(body === undefined ? {} : { "content-type": "application/json" }),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    if (!res.ok) {
      // The token travels only in the request header; error text is the
      // response body, which GitHub never echoes credentials into.
      const detail = (await res.text().catch(() => "")).slice(0, 300);
      throw new Error(`GitHub delivery: ${method} ${path || "/"} failed (${res.status}): ${detail}`);
    }
    return (await res.json()) as T;
  }
}

/** Mirror `LocalDirectoryDelivery`'s refusal: no escapes, no absolute paths. */
function safeRepoPath(file: GeneratedFile): string {
  const path = file.path;
  const segments = path.split("/");
  if (
    path.startsWith("/") ||
    path.includes("\\") ||
    segments.some((s) => s === ".." || s === "" || s === ".")
  ) {
    throw new Error(`refusing to deliver an unsafe path: ${path}`);
  }
  return path;
}

function normalizePrefix(prefix: string | undefined): string {
  if (!prefix) return "";
  const trimmed = prefix.replace(/^\/+|\/+$/g, "");
  if (trimmed.split("/").some((s) => s === ".." || s === "." || s === "")) {
    throw new Error(`unsafe pathPrefix: ${prefix}`);
  }
  return `${trimmed}/`;
}

/**
 * Build a GitHub delivery from the environment, or `null` to deliver locally.
 *
 * `ANDROMEDA_DELIVERY_REPO` is `owner/repo`; `GITHUB_TOKEN` authenticates.
 * Optional `ANDROMEDA_DELIVERY_BASE` targets a branch other than the
 * repository's default. Takes the environment as a plain object, like
 * `supabaseStoreFromEnv`, so it stays testable.
 */
export function githubDeliveryFromEnv(
  env: Record<string, string | undefined>,
  fetchImpl?: typeof fetch,
): GitHubPullRequestDelivery | null {
  const target = env.ANDROMEDA_DELIVERY_REPO;
  const token = env.GITHUB_TOKEN;
  if (!target || !token) return null;
  const [owner, repo, ...rest] = target.split("/");
  if (!owner || !repo || rest.length > 0) {
    throw new Error(`ANDROMEDA_DELIVERY_REPO must be "owner/repo", got "${target}"`);
  }
  return new GitHubPullRequestDelivery({
    owner,
    repo,
    token,
    ...(env.ANDROMEDA_DELIVERY_BASE ? { baseBranch: env.ANDROMEDA_DELIVERY_BASE } : {}),
    ...(fetchImpl ? { fetchImpl } : {}),
  });
}
