import type { ProjectSpec } from "../spec/types.ts";
import type { GeneratedFile, TemplateDefinition } from "./types.ts";
import { envExample, routeDirectory, stableJson, tsType } from "./render.ts";
import { migrationSql } from "./sql.ts";

/**
 * Dependency pins.
 *
 * Exact versions, checked against the registry when the template was written.
 * TypeScript is held at 5.x deliberately: the generated code relies on
 * `erasableSyntaxOnly` semantics that the scaffold is tested against.
 */
const DEPENDENCIES = {
  next: "16.3.1",
  react: "19.2.8",
  "react-dom": "19.2.8",
  "@supabase/supabase-js": "2.112.3",
  "@supabase/ssr": "0.12.4",
};

const DEV_DEPENDENCIES = {
  typescript: "5.9.3",
  "@types/node": "26.2.0",
  "@types/react": "19.2.18",
  "@types/react-dom": "19.2.4",
};

export const nextSupabaseApp: TemplateDefinition = {
  id: "next-supabase-app",
  version: "1.0.0",
  description:
    "Next.js App Router on Vercel with Supabase Postgres, auth and row-level security.",
  dependencies: DEPENDENCIES,
  devDependencies: DEV_DEPENDENCIES,
  render(spec: ProjectSpec): GeneratedFile[] {
    const files: GeneratedFile[] = [
      { path: "package.json", contents: packageJson(spec) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "next.config.mjs", contents: nextConfig() },
      { path: ".gitignore", contents: gitignore() },
      { path: ".env.example", contents: envExample(spec) },
      { path: "README.md", contents: readme(spec) },
      { path: ".github/workflows/ci.yml", contents: ciWorkflow() },
      { path: "supabase/migrations/0001_init.sql", contents: migrationSql(spec) },
      { path: "features/contract.ts", contents: featureContract() },
      { path: "lib/types.ts", contents: entityTypes(spec) },
      { path: "lib/supabase.ts", contents: supabaseClient(spec) },
      { path: "app/layout.tsx", contents: layout(spec) },
      { path: "app/page.tsx", contents: homePage(spec) },
      { path: "app/api/health/route.ts", contents: healthRoute(spec) },
    ];

    for (const route of spec.routes) {
      if (!route.feature) continue;
      files.push({
        path: `${routeDirectory(route.path)}/route.ts`,
        contents: featureRoute(spec, route.path),
      });
    }
    return files;
  },
};

function packageJson(spec: ProjectSpec): string {
  return stableJson({
    name: spec.name,
    version: "0.1.0",
    private: true,
    type: "module",
    engines: { node: ">=22.18.0" },
    // Node's own subpath imports, so generated feature modules resolve under
    // bare `node --test` with nothing installed. A tsconfig path alias would
    // typecheck but not run.
    imports: { "#features/*": "./features/*", "#lib/*": "./lib/*" },
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      typecheck: "tsc --noEmit",
      test: 'node --test "features/**/*.test.ts"',
    },
    dependencies: DEPENDENCIES,
    devDependencies: DEV_DEPENDENCIES,
  });
}

function tsconfig(): string {
  return stableJson({
    compilerOptions: {
      target: "ES2023",
      lib: ["ES2023", "DOM", "DOM.Iterable"],
      module: "NodeNext",
      moduleResolution: "nodenext",
      allowImportingTsExtensions: true,
      rewriteRelativeImportExtensions: true,
      verbatimModuleSyntax: true,
      erasableSyntaxOnly: true,
      jsx: "preserve",
      noEmit: true,
      strict: true,
      noUncheckedIndexedAccess: true,
      skipLibCheck: true,
      incremental: true,
      plugins: [{ name: "next" }],
    },
    include: ["**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  });
}

const nextConfig = (): string =>
  `/** @type {import("next").NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`;

const gitignore = (): string =>
  `node_modules/
.next/
out/
.env
.env.local
*.tsbuildinfo
.DS_Store
`;

const ciWorkflow = (): string =>
  `name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      # ci, not install: fail on a lockfile that drifted from package.json
      # rather than silently resolving something new.
      - run: npm ci
      - run: npm run typecheck
      - run: npm test
`;

function readme(spec: ProjectSpec): string {
  const entities = spec.entities.map((e) => `- \`${e.name}\` — ${e.summary}`).join("\n");
  const features = spec.features.map((f) => `- \`${f.id}\` — ${f.summary}`).join("\n");
  const routes = spec.routes
    .map((r) => `- \`${r.method} ${r.path}\` — ${r.summary}`)
    .join("\n");

  return `# ${spec.name}

${spec.summary}

Generated by the Andromeda auto-builder from \`project.yaml\`. The scaffold
(config, schema, row-level security, CI) came from the pinned
\`next-supabase-app\` template; the modules under \`features/\` were generated
and had to pass their own test suite before this repository was proposed for
review.

## Getting started

\`\`\`bash
npm ci
cp .env.example .env.local   # fill in the values
npx supabase db push          # apply supabase/migrations
npm test
npm run dev
\`\`\`

## Data model

${entities || "_No tables._"}

Every table has row-level security enabled. Tables with an owner column carry
owner-scoped policies; tables without one have no policy, which denies all
client access by default.

## Features

${features || "_No generated features._"}

Each feature module exports \`handle(input)\` from \`features/contract.ts\` and
is covered by \`features/<id>.test.ts\`.

## Routes

${routes || "_No routes._"}
`;
}

const featureContract = (): string =>
  `/**
 * The contract between generated business logic and the scaffold.
 *
 * Route handlers, auth and persistence are template-provided; a feature module
 * is a pure function from a request to a response. Keeping the boundary this
 * narrow is what makes generated code testable without a server, a database or
 * a network.
 */
export interface FeatureInput {
  method: string;
  path: string;
  query: Record<string, string>;
  body: unknown;
  /** Authenticated user id, or null for an anonymous request. */
  userId: string | null;
}

export interface FeatureResult {
  status: number;
  body: unknown;
}

export type FeatureHandler = (input: FeatureInput) => Promise<FeatureResult>;
`;

function entityTypes(spec: ProjectSpec): string {
  const blocks = spec.entities.map((entity) => {
    const fields = entity.fields
      .map((f) => `  ${f.name}${f.required ? "" : "?"}: ${tsType(f.type)};`)
      .join("\n");
    return `/** ${entity.summary} */
export interface ${pascal(entity.name)} {
  id: string;
${fields}
  created_at: string;
  updated_at: string;
}`;
  });

  return `// Row types matching supabase/migrations/0001_init.sql.
// Regenerated from project.yaml; edit the spec, not this file.

${blocks.join("\n\n")}${blocks.length ? "\n" : ""}`;
}

function supabaseClient(spec: ProjectSpec): string {
  return `import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

/**
 * Request-scoped Supabase client for ${spec.name}.
 *
 * This uses the anon key and forwards the caller's session, so every query
 * runs as the signed-in user and row-level security applies. Never swap in the
 * service-role key here — it bypasses RLS entirely.
 */
export async function supabaseServer() {
  const cookieStore = await cookies();
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) {
    throw new Error(
      "NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY must be set",
    );
  }

  return createServerClient(url, key, {
    cookies: {
      getAll: () => cookieStore.getAll(),
      setAll: (list) => {
        for (const { name, value, options } of list) {
          cookieStore.set(name, value, options);
        }
      },
    },
  });
}
`;
}

function layout(spec: ProjectSpec): string {
  return `import type { ReactNode } from "react";

export const metadata = {
  title: ${JSON.stringify(spec.name)},
  description: ${JSON.stringify(spec.summary)},
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function homePage(spec: ProjectSpec): string {
  return `export default function Home() {
  return (
    <main>
      <h1>${escapeJsx(spec.name)}</h1>
      <p>${escapeJsx(spec.summary)}</p>
    </main>
  );
}
`;
}

function healthRoute(spec: ProjectSpec): string {
  return `export async function GET() {
  return Response.json({ ok: true, service: ${JSON.stringify(spec.name)} });
}
`;
}

/**
 * Deterministic adapter between an HTTP route and a generated feature module.
 * The model never writes this part, so request parsing, the auth lookup and
 * error shaping are identical in every generated project.
 */
function featureRoute(spec: ProjectSpec, path: string): string {
  const methods = spec.routes
    .filter((r) => r.path === path && r.feature)
    .map((r) => ({ method: r.method, feature: r.feature }));

  const imports = [...new Set(methods.map((m) => m.feature))]
    .map((feature) => `import { handle as ${camel(feature)} } from "#features/${feature}.ts";`)
    .join("\n");

  const handlers = methods
    .map(
      ({ method, feature }) => `export async function ${method}(request: Request) {
  return run(request, ${camel(feature)});
}`,
    )
    .join("\n\n");

  return `import type { FeatureHandler } from "#features/contract.ts";
import { supabaseServer } from "#lib/supabase.ts";
${imports}

async function run(request: Request, handler: FeatureHandler) {
  const url = new URL(request.url);
  let body: unknown = null;
  if (request.method !== "GET" && request.method !== "DELETE") {
    try {
      body = await request.json();
    } catch {
      return Response.json({ error: "request body must be JSON" }, { status: 400 });
    }
  }

  const supabase = await supabaseServer();
  const { data } = await supabase.auth.getUser();

  const result = await handler({
    method: request.method,
    path: url.pathname,
    query: Object.fromEntries(url.searchParams),
    body,
    userId: data.user?.id ?? null,
  });

  return Response.json(result.body, { status: result.status });
}

${handlers}
`;
}

const pascal = (name: string): string =>
  name
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join("");

const camel = (name: string): string => {
  const p = pascal(name);
  return `${p.slice(0, 1).toLowerCase()}${p.slice(1)}`;
};

/** JSX text is not HTML: braces and angle brackets become string expressions. */
const escapeJsx = (text: string): string =>
  text.replace(/[{}<>]/g, (c) => `{${JSON.stringify(c)}}`);
