import type { ProjectSpec } from "../spec/types.ts";
import type { GeneratedFile, TemplateDefinition } from "./types.ts";
import { envExample, featureContract, stableJson } from "./render.ts";
import { migrationSql } from "./sql.ts";

const DEPENDENCIES = {};
const DEV_DEPENDENCIES = {
  "@types/node": "22.10.5",
  typescript: "5.9.3",
};

/**
 * Plain Node HTTP service — no framework, no platform.
 *
 * The third point on the deployment triangle: `next-supabase-app` is a full
 * web app on Vercel, `worker-api` is edge endpoints on Cloudflare, and this is
 * the service you run on a box you already have. Zero runtime dependencies,
 * TypeScript stripped natively by Node 22, so `npm ci && node src/server.ts`
 * is the entire operational story.
 *
 * Shares `features/contract.ts` with the other templates: the server owns
 * request plumbing, the model owns pure logic behind the test-gate, and a
 * generated feature module is portable between all three scaffolds.
 */
export const nodeService: TemplateDefinition = {
  id: "node-service",
  version: "1.0.0",
  description:
    "Self-hosted Node 22 HTTP service with Supabase Postgres migrations. No framework; runs anywhere Node runs.",
  dependencies: DEPENDENCIES,
  devDependencies: DEV_DEPENDENCIES,
  render(spec: ProjectSpec): GeneratedFile[] {
    return [
      { path: "package.json", contents: packageJson(spec) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: ".gitignore", contents: "node_modules/\n.env\n.env.local\n*.log\n" },
      { path: ".env.example", contents: envExample(spec) },
      { path: "README.md", contents: readme(spec) },
      { path: ".github/workflows/ci.yml", contents: ciWorkflow() },
      { path: "supabase/migrations/0001_init.sql", contents: migrationSql(spec) },
      { path: "features/contract.ts", contents: featureContract() },
      { path: "src/router.ts", contents: router(spec) },
      { path: "src/server.ts", contents: server(spec) },
    ];
  },
};

function packageJson(spec: ProjectSpec): string {
  return stableJson({
    name: spec.name,
    version: "0.1.0",
    private: true,
    type: "module",
    engines: { node: ">=22.18.0" },
    imports: { "#features/*": "./features/*" },
    scripts: {
      dev: "node --watch src/server.ts",
      start: "node src/server.ts",
      typecheck: "tsc --noEmit",
      test: 'node --test "features/**/*.test.ts"',
    },
    dependencies: DEPENDENCIES,
    devDependencies: DEV_DEPENDENCIES,
  });
}

const tsconfig = (): string =>
  stableJson({
    compilerOptions: {
      target: "ES2023",
      lib: ["ES2023"],
      module: "NodeNext",
      moduleResolution: "nodenext",
      // No rewriteRelativeImportExtensions: this scaffold never emits (Node
      // strips types at run time), and with it enabled tsc rejects every
      // non-relative `#features/*.ts` import with TS2877.
      allowImportingTsExtensions: true,
      verbatimModuleSyntax: true,
      erasableSyntaxOnly: true,
      noEmit: true,
      strict: true,
      noUncheckedIndexedAccess: true,
      skipLibCheck: true,
      types: ["node"],
    },
    include: ["**/*.ts"],
    exclude: ["node_modules"],
  });

const ciWorkflow = (): string =>
  `name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      # A rendered scaffold cannot include a real lockfile. Run \`npm install\`
      # locally, commit package-lock.json, then switch this to \`npm ci\` so a
      # drifted dependency fails the build.
      - run: npm install
      - run: npm run typecheck
      - run: npm test
`;

function readme(spec: ProjectSpec): string {
  return `# ${spec.name}

${spec.summary}

Self-hosted Node service generated by the Andromeda auto-builder. Request
plumbing comes from the pinned \`node-service\` template; \`features/\` holds
generated logic that passed its frozen test suite before review. There is no
build step: Node 22 runs the TypeScript directly.

\`\`\`bash
npm ci
npm test
npm run dev        # or: npm start
\`\`\`

The server listens on \`PORT\` (default 3000) and answers \`GET /health\`.
Apply \`supabase/migrations/\` to your Postgres before pointing the service at
it.

## Identity

Features receive \`userId\` from the \`x-user-id\` header **only** when the
request also carries \`x-proxy-secret\` matching the \`PROXY_AUTH_SECRET\`
environment variable — the contract for running behind a reverse proxy that
authenticates users and stamps the header. With no secret configured, every
request is anonymous (\`userId: null\`). Never expose the service directly
while trusting \`x-user-id\` without that secret: a bare header is not
authentication.
`;
}

function router(spec: ProjectSpec): string {
  const routed = spec.routes.filter((r) => r.feature);
  const bindings = bindingNames([...new Set(routed.map((r) => r.feature))]);
  const imports = [...bindings]
    .map(([f, name]) => `import { handle as ${name} } from "#features/${f}.ts";`)
    .join("\n");
  const table = routed
    .map((r) => `  { method: ${JSON.stringify(r.method)}, path: ${JSON.stringify(r.path)}, handler: ${bindings.get(r.feature)} },`)
    .join("\n");

  return `import type { FeatureHandler } from "#features/contract.ts";
${imports}

export interface Route {
  method: string;
  path: string;
  handler: FeatureHandler;
}

export const routes: Route[] = [
${table}
];
`;
}

function server(spec: ProjectSpec): string {
  return `import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { routes } from "./router.ts";

const MAX_BODY_BYTES = 1_000_000;

/**
 * Identity contract: \`x-user-id\` is honored only when the request also
 * carries \`x-proxy-secret\` matching PROXY_AUTH_SECRET — proof it came
 * through your authenticating proxy. No secret configured means every
 * request is anonymous; a bare header is never authentication.
 */
const proxySecret = process.env.PROXY_AUTH_SECRET ?? "";

function constantTimeEqual(a: string, b: string): boolean {
  const encoder = new TextEncoder();
  const left = encoder.encode(a);
  const right = encoder.encode(b);
  let diff = left.length ^ right.length;
  for (let i = 0; i < left.length; i++) {
    diff |= (left[i] as number) ^ (right[i % right.length] ?? 0);
  }
  return diff === 0 && left.length > 0;
}

function resolveUserId(req: IncomingMessage): string | null {
  if (proxySecret === "") return null;
  const supplied = req.headers["x-proxy-secret"];
  if (typeof supplied !== "string" || !constantTimeEqual(supplied, proxySecret)) return null;
  const userId = req.headers["x-user-id"];
  return typeof userId === "string" && userId !== "" ? userId : null;
}

/**
 * Deterministic request plumbing for ${spec.name}. Generated features never
 * parse requests or shape errors themselves.
 */
const server = createServer(async (req: IncomingMessage, res: ServerResponse) => {
  const reply = (status: number, body: unknown): void => {
    // Serialize before writing the head: a body JSON cannot represent must
    // become a clean 500, not a crash after the status line is on the wire.
    let payload: string;
    try {
      payload = JSON.stringify(body) ?? "null";
    } catch (err) {
      console.error("unserializable response body", err);
      status = 500;
      payload = '{"error":"internal error"}';
    }
    res.writeHead(status, { "content-type": "application/json; charset=utf-8" });
    res.end(\`\${payload}\\n\`);
  };

  try {
    let url: URL;
    try {
      url = new URL(req.url ?? "/", \`http://\${req.headers.host ?? "localhost"}\`);
    } catch {
      return reply(400, { error: "invalid request target" });
    }

    if (url.pathname === "/health") {
      return reply(200, { ok: true, service: ${JSON.stringify(spec.name)} });
    }

    const route = routes.find((r) => r.method === req.method && r.path === url.pathname);
    if (!route) return reply(404, { error: "not found" });

    let body: unknown = null;
    if (req.method !== "GET" && req.method !== "DELETE") {
      const chunks: Buffer[] = [];
      let size = 0;
      for await (const chunk of req) {
        size += (chunk as Buffer).length;
        if (size > MAX_BODY_BYTES) return reply(413, { error: "request body too large" });
        chunks.push(chunk as Buffer);
      }
      const raw = Buffer.concat(chunks).toString("utf8");
      if (raw !== "") {
        try {
          body = JSON.parse(raw);
        } catch {
          return reply(400, { error: "request body must be JSON" });
        }
      }
    }

    const result = await route.handler({
      method: req.method ?? "GET",
      path: url.pathname,
      query: Object.fromEntries(url.searchParams),
      body,
      userId: resolveUserId(req),
    });
    return reply(result.status, result.body);
  } catch (err) {
    // Log the detail; clients get a generic error rather than internals.
    console.error(err);
    if (!res.headersSent) reply(500, { error: "internal error" });
    else res.end();
  }
});

const port = Number(process.env.PORT ?? 3000);
server.listen(port, () => {
  console.log(\`${spec.name} listening on http://localhost:\${port}\`);
});
`;
}

const camel = (name: string): string => {
  const pascal = name
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join("");
  return `${pascal.slice(0, 1).toLowerCase()}${pascal.slice(1)}`;
};

/**
 * Unique import binding per feature id. Distinct slugs can camel-case to the
 * same identifier ("a-b" and "a--b"), which would render a router that
 * declares one binding twice and fails to parse.
 */
function bindingNames(features: string[]): Map<string, string> {
  const names = new Map<string, string>();
  const taken = new Set<string>();
  for (const feature of features) {
    let name = camel(feature);
    for (let n = 2; taken.has(name); n++) name = `${camel(feature)}${n}`;
    taken.add(name);
    names.set(feature, name);
  }
  return names;
}
