import type { EntitySpec, ProjectSpec } from "../spec/types.ts";
import { sqlType } from "./render.ts";

/**
 * Generate the initial migration.
 *
 * Written by hand and rendered from validated data — never generated by a
 * model. Two defaults here are deliberate and load-bearing:
 *
 * - Row-level security is enabled on every table. A table with an `ownerField`
 *   gets owner-scoped policies; a table without one gets no policy at all,
 *   which in Postgres means deny-all. Forgetting to configure access therefore
 *   locks the table down instead of exposing it.
 * - `(select auth.uid())` is wrapped in a subquery so Postgres evaluates it
 *   once per statement rather than once per row.
 */
export function migrationSql(spec: ProjectSpec): string {
  const ordered = topologicallySort(spec.entities);
  const out: string[] = [
    `-- Initial schema for ${spec.name}.`,
    "-- Generated from project.yaml by the Andromeda template layer. Edit the spec, not this file.",
    "",
    'create extension if not exists "pgcrypto";',
    "",
    updatedAtFunction(),
    "",
  ];

  for (const entity of ordered) {
    out.push(createTable(entity), "");
    out.push(`alter table public.${entity.name} enable row level security;`, "");
    out.push(...policies(entity), "");
    out.push(updatedAtTrigger(entity), "");
  }

  return `${out.join("\n").trimEnd()}\n`;
}

function createTable(entity: EntitySpec): string {
  const columns: string[] = ["  id uuid primary key default gen_random_uuid(),"];

  for (const field of entity.fields) {
    const parts = [`  ${field.name} ${sqlType(field.type)}`];
    if (field.required) parts.push("not null");
    if (field.unique) parts.push("unique");
    if (field.references) {
      parts.push(`references public.${field.references}(id) on delete cascade`);
    }
    columns.push(`${parts.join(" ")},`);
  }

  columns.push("  created_at timestamptz not null default now(),");
  columns.push("  updated_at timestamptz not null default now()");

  return [
    `-- ${entity.summary}`,
    `create table if not exists public.${entity.name} (`,
    ...columns,
    ");",
  ].join("\n");
}

function policies(entity: EntitySpec): string[] {
  if (!entity.ownerField) {
    return [
      `-- No ownerField on ${entity.name}: RLS is on with no policy, so every`,
      "-- client request is denied. Add a policy here, or set ownerField in the spec.",
    ];
  }
  const t = entity.name;
  const owner = entity.ownerField;
  const uid = "(select auth.uid())";
  return [
    `create policy "${t}_select_own" on public.${t}`,
    `  for select using (${uid} = ${owner});`,
    `create policy "${t}_insert_own" on public.${t}`,
    `  for insert with check (${uid} = ${owner});`,
    `create policy "${t}_update_own" on public.${t}`,
    `  for update using (${uid} = ${owner}) with check (${uid} = ${owner});`,
    `create policy "${t}_delete_own" on public.${t}`,
    `  for delete using (${uid} = ${owner});`,
  ];
}

function updatedAtFunction(): string {
  return [
    "create or replace function public.set_updated_at()",
    "returns trigger language plpgsql as $$",
    "begin",
    "  new.updated_at = now();",
    "  return new;",
    "end;",
    "$$;",
  ].join("\n");
}

function updatedAtTrigger(entity: EntitySpec): string {
  return [
    `drop trigger if exists ${entity.name}_set_updated_at on public.${entity.name};`,
    `create trigger ${entity.name}_set_updated_at`,
    `  before update on public.${entity.name}`,
    "  for each row execute function public.set_updated_at();",
  ].join("\n");
}

/**
 * Order tables so a foreign key never points at a table that does not exist yet.
 * Self-references are legal inline and are ignored here; a genuine cycle
 * between two tables cannot be expressed as inline constraints and is rejected.
 */
export function topologicallySort(entities: EntitySpec[]): EntitySpec[] {
  const byName = new Map(entities.map((e) => [e.name, e]));
  const visited = new Set<string>();
  const onStack = new Set<string>();
  const ordered: EntitySpec[] = [];

  const visit = (entity: EntitySpec, path: string[]): void => {
    if (visited.has(entity.name)) return;
    if (onStack.has(entity.name)) {
      throw new Error(
        `circular foreign keys between tables: ${[...path, entity.name].join(" -> ")}`,
      );
    }
    onStack.add(entity.name);
    for (const field of entity.fields) {
      if (!field.references || field.references === entity.name) continue;
      const target = byName.get(field.references);
      if (target) visit(target, [...path, entity.name]);
    }
    onStack.delete(entity.name);
    visited.add(entity.name);
    ordered.push(entity);
  };

  for (const entity of entities) visit(entity, []);
  return ordered;
}
