import type { ProjectSpec } from "../spec/types.ts";
import type { GeneratedFile, TemplateDefinition } from "./types.ts";
import { envExample, stableJson } from "./render.ts";
import { migrationSql } from "./sql.ts";

const DEPENDENCIES = {};
const DEV_DEPENDENCIES = {
  wrangler: "4.125.0",
  "@cloudflare/workers-types": "5.20260820.1",
  typescript: "5.9.3",
};

/**
 * Headless API on Cloudflare Workers.
 *
 * Shares the `features/contract.ts` boundary with the Next.js template, so a
 * generated feature module and its tests are portable between the two: the
 * template owns routing and the runtime, the model owns pure logic only.
 */
export const workerApi: TemplateDefinition = {
  id: "worker-api",
  version: "1.0.0",
  description:
    "Cloudflare Workers HTTP API with Supabase Postgres. No UI; edge-deployed endpoints only.",
  dependencies: DEPENDENCIES,
  devDependencies: DEV_DEPENDENCIES,
  render(spec: ProjectSpec): GeneratedFile[] {
    return [
      { path: "package.json", contents: packageJson(spec) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "wrangler.toml", contents: wranglerToml(spec) },
      { path: ".gitignore", contents: ".wrangler/\nnode_modules/\n.env\n.dev.vars\n" },
      { path: ".env.example", contents: envExample(spec) },
      { path: "README.md", contents: readme(spec) },
      { path: ".github/workflows/ci.yml", contents: ciWorkflow() },
      { path: "supabase/migrations/0001_init.sql", contents: migrationSql(spec) },
      { path: "features/contract.ts", contents: featureContract() },
      { path: "src/router.ts", contents: router(spec) },
      { path: "src/index.ts", contents: entrypoint(spec) },
    ];
  },
};

function packageJson(spec: ProjectSpec): string {
  return stableJson({
    name: spec.name,
    version: "0.1.0",
    private: true,
    type: "module",
    engines: { node: ">=22.18.0" },
    imports: { "#features/*": "./features/*" },
    scripts: {
      dev: "wrangler dev",
      deploy: "wrangler deploy",
      typecheck: "tsc --noEmit",
      test: 'node --test "features/**/*.test.ts"',
    },
    dependencies: DEPENDENCIES,
    devDependencies: DEV_DEPENDENCIES,
  });
}

const tsconfig = (): string =>
  stableJson({
    compilerOptions: {
      target: "ES2023",
      lib: ["ES2023"],
      module: "NodeNext",
      moduleResolution: "nodenext",
      allowImportingTsExtensions: true,
      rewriteRelativeImportExtensions: true,
      verbatimModuleSyntax: true,
      erasableSyntaxOnly: true,
      noEmit: true,
      strict: true,
      noUncheckedIndexedAccess: true,
      skipLibCheck: true,
      types: ["@cloudflare/workers-types"],
    },
    include: ["**/*.ts"],
    exclude: ["node_modules"],
  });

function wranglerToml(spec: ProjectSpec): string {
  const vars = spec.env
    .filter((e) => !e.secret)
    .map((e) => `# ${e.name} — ${e.description}`)
    .join("\n");
  const secrets = spec.env
    .filter((e) => e.secret)
    .map((e) => `#   wrangler secret put ${e.name}`)
    .join("\n");

  return `name = "${spec.name}"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
${vars || "# no plain-text vars"}

# Secrets are never written to this file. Set them with:
${secrets || "#   (no secrets declared)"}
`;
}

const ciWorkflow = (): string =>
  `name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npm run typecheck
      - run: npm test
`;

function readme(spec: ProjectSpec): string {
  return `# ${spec.name}

${spec.summary}

Cloudflare Workers API generated by the Andromeda auto-builder. Routing and the
runtime come from the pinned \`worker-api\` template; \`features/\` holds
generated logic that passed its test suite before review.

\`\`\`bash
npm ci
npm test
npx wrangler dev
\`\`\`
`;
}

const featureContract = (): string =>
  `/** Shared with every Andromeda template: a feature is a pure request handler. */
export interface FeatureInput {
  method: string;
  path: string;
  query: Record<string, string>;
  body: unknown;
  userId: string | null;
}

export interface FeatureResult {
  status: number;
  body: unknown;
}

export type FeatureHandler = (input: FeatureInput) => Promise<FeatureResult>;
`;

function router(spec: ProjectSpec): string {
  const routed = spec.routes.filter((r) => r.feature);
  const imports = [...new Set(routed.map((r) => r.feature))]
    .map((f) => `import { handle as ${camel(f)} } from "#features/${f}.ts";`)
    .join("\n");
  const table = routed
    .map((r) => `  { method: ${JSON.stringify(r.method)}, path: ${JSON.stringify(r.path)}, handler: ${camel(r.feature)} },`)
    .join("\n");

  return `import type { FeatureHandler } from "#features/contract.ts";
${imports}

export interface Route {
  method: string;
  path: string;
  handler: FeatureHandler;
}

export const routes: Route[] = [
${table}
];
`;
}

function entrypoint(spec: ProjectSpec): string {
  return `import { routes } from "./router.ts";

/**
 * Deterministic request plumbing for ${spec.name}. Generated features never
 * parse requests or shape errors themselves.
 */
export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ ok: true, service: ${JSON.stringify(spec.name)} });
    }

    const route = routes.find(
      (r) => r.method === request.method && r.path === url.pathname,
    );
    if (!route) return Response.json({ error: "not found" }, { status: 404 });

    let body: unknown = null;
    if (request.method !== "GET" && request.method !== "DELETE") {
      try {
        body = await request.json();
      } catch {
        return Response.json({ error: "request body must be JSON" }, { status: 400 });
      }
    }

    const result = await route.handler({
      method: request.method,
      path: url.pathname,
      query: Object.fromEntries(url.searchParams),
      body,
      userId: request.headers.get("x-user-id"),
    });

    return Response.json(result.body, { status: result.status });
  },
};
`;
}

const camel = (name: string): string => {
  const pascal = name
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join("");
  return `${pascal.slice(0, 1).toLowerCase()}${pascal.slice(1)}`;
};
